name: Display uname -a

on:
  push:
    branches:
      - main

jobs:
  display-uname:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display uname -a
        run: |
          uname -a
